-- <SELECT>
SELECT *
FROM EMPLOYEE;
-- *: 모든 자료 조회할 때 사용

SELECT EMP_ID, EMP_NAME, SALARY
FROM EMPLOYEE;

SELECT *
FROM JOB;

SELECT *
FROM DEPARTMENT;

SELECT DEPT_ID, DEPT_TITLE
FROM DEPARTMENT;

SELECT EMP_NAME, EMAIL, PHONE, HIRE_DATE, SALARY
FROM EMPLOYEE;

-- <산술연산>
SELECT EMP_NAME, SALARY * 12
FROM EMPLOYEE;

SELECT EMP_NAME, SALARY, BONUS, (SALARY + (SALARY * BONUS)) * 12 || '원' AS "보너스연봉"
FROM EMPLOYEE;

SELECT DISTINCT JOB_CODE
FROM EMPLOYEE;

SELECT DISTINCT DEPT_CODE
FROM EMPLOYEE;

-- DISTINCT는 절에서 단 한번만 기술가능

SELECT *
FROM EMPLOYEE
WHERE DEPT_CODE = 'D9';

SELECT EMP_NAME, SALARY, DEPT_CODE
FROM EMPLOYEE
WHERE DEPT_CODE = 'D1';

SELECT EMP_ID, EMP_NAME, DEPT_CODE
FROM EMPLOYEE
WHERE DEPT_CODE != 'D1';
-- 같지 않다: !=, ^=, <>

-- SELECT 절에서 지은 별칭은 WHERE 절에서 사용할 수 없다
-- 쿼리의 실행순서가 FROM -> WHERE -> SELECT절 순서이기 때문

-- <BETWEEN A AND B>
SELECT EMP_NAME, EMP_ID, SALARY || '원' AS "SALARY"
FROM EMPLOYEE
WHERE SALARY BETWEEN 3000000 AND 7000000;

-- <NOT>: 컬럼명 뒤에 사용할 수도 BETWEEN 앞에 사용할 수도 있음

SELECT EMP_NAME, EMP_ID, SALARY || '원' AS "SALARY"
FROM EMPLOYEE
WHERE NOT SALARY BETWEEN 3000000 AND 7000000;

SELECT EMP_NAME, EMP_ID, SALARY || '원' AS "SALARY"
FROM EMPLOYEE
WHERE SALARY NOT BETWEEN 3000000 AND 7000000;

-- <와일드카드>
SELECT EMP_NAME, EMP_ID, PHONE
FROM EMPLOYEE
WHERE EMP_NAME LIKE '%하';
-- 하로 끝나는 값 찾기

SELECT EMP_NAME, EMP_ID, PHONE
FROM EMPLOYEE
WHERE EMP_NAME LIKE '하%';
-- 하로 시작하는 값 찾기

SELECT EMP_NAME, EMP_ID, PHONE
FROM EMPLOYEE
WHERE EMP_NAME LIKE '%하%';
-- 하가 들어가는 값 찾기

-- <와일드카드 특이케이스>
SELECT EMP_ID, PHONE, EMAIL
FROM EMPLOYEE
WHERE EMAIL LIKE '___$_%' ESCAPE '$';


-- <IS NULL, IS NOT NULL>
SELECT EMP_ID, EMP_NAME, SALARY, BONUS
FROM EMPLOYEE
WHERE BONUS IS NULL;

SELECT EMP_ID, EMP_NAME, SALARY, BONUS
FROM EMPLOYEE
WHERE BONUS IS NOT NULL;
-- WHERE NOT BONUS IS NULL;

/* 연산자 우선순위
    1. ()
    2. 산술연산자
    3. 연결연산자 ||
    4. IS NULL / LIKE /IN
    5. BETWEEN A AND B
    6. NOT
    7. AND
    8. OR (AND가 OR보다 우선함)
*/

