SELECT SYSDATE
FROM DUAL;
-- LENGTH / LENGTHB
SELECT LENGTH('오라클'), LENGTHB('오라클')
FROM DUAL;

SELECT LENGTH('oracle'), LENGTHB('oracle')
FROM DUAL;

SELECT EMP_NAME, LENGTH(EMP_NAME), LENGTHB(EMP_NAME), EMAIL, LENGTH(EMAIL), LENGTHB(EMAIL)
FROM EMPLOYEE;

-- INSTR
SELECT INSTR('AAAAAVBBBBBCCCCCE', 'V') FROM DUAL;
SELECT INSTR('AAAAAVBBBBBCCCCCE', 'E') FROM DUAL;
SELECT INSTR('AAAAAVBBBBBCCCCCE', 'V', -1) FROM DUAL;
SELECT INSTR('AAAAAVBBBBBCCCCCE', 'B', 1, 2) FROM DUAL;

SELECT EMAIL, INSTR(EMAIL, '_'), INSTR(EMAIL, '@')
FROM EMPLOYEE;

-- SUBSTR
SELECT SUBSTR('ABCDEFG', 3)
FROM DUAL;

SELECT SUBSTR('SGDSHSDHS', 1, 4)
FROM DUAL;

SELECT EMP_NAME, SUBSTR(EMP_NO, 8, 1)
FROM EMPLOYEE
WHERE SUBSTR(EMP_NO, 8, 1) IN ('1', '3');

SELECT EMP_NAME, EMAIL, SUBSTR(EMAIL, 1, INSTR(EMAIL, '@')-1)
FROM EMPLOYEE;

-- LPAD, RPAD
SELECT EMP_NAME, LPAD(EMP_NAME, 15)
FROM EMPLOYEE;

-- LTRIM / RTIM
SELECT LTRIM('@@@@@III' ,'@') FROM DUAL;
SELECT RTRIM('QWER13254' ,'12345') FROM DUAL;

-- TRIM
SELECT TRIM(LEADING 'Q' FROM 'QWER123') FROM DUAL;

-- LOWER / UPPER / INITCAP
SELECT LOWER('HI') FROM DUAL;
SELECT UPPER('hi') FROM DUAL;
SELECT INITCAP('QWEGSAY') FROM DUAL;

-- CONCAT
SELECT CONCAT('QWER', '123') FROM DUAL;

-- REPLACE
SELECT REPLACE(EMP_NAME, '하', '허')
FROM EMPLOYEE;

--------------------------------------------------------------------------
-- 숫자처리
SELECT ABS(-123) FROM DUAL;
SELECT MOD(20, 3) FROM DUAL;
SELECT ROUND(145.367, 2) FROM DUAL;
SELECT CEIL(132.222) FROM DUAL;
SELECT FLOOR(132.99) FROM DUAL;
SELECT TRUNC (132.99, 1) FROM DUAL;

---------------------------------------------------------------------------
-- 날짜처리
SELECT EMP_NAME, FLOOR(MONTHS_BETWEEN(SYSDATE, HIRE_DATE))
FROM EMPLOYEE;

SELECT EMP_NAME, ADD_MONTHS(SYSDATE, 24)
FROM EMPLOYEE;

SELECT NEXT_DAY(SYSDATE, 4) FROM DUAL;

SELECT LAST_DAY(ADD_MONTHS(SYSDATE, 3)) FROM DUAL;

SELECT EXTRACT(YEAR FROM SYSDATE) AS "년" FROM DUAL;

---------------------------------------------------------------------------
-- 형변환 함수
SELECT TO_CHAR(SYSDATE) FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY"년" MM"월" DD"일"') FROM DUAL;
SELECT TO_CHAR(12345, '999,999') FROM DUAL;
SELECT TO_CHAR(12345, 'L999,999') FROM DUAL;
SELECT TO_CHAR(12345, '999,999') FROM DUAL;

SELECT TO_DATE(221128) FROM DUAL;
SELECT TO_DATE(121212, 'YYMMDD') FROM DUAL;
SELECT TO_DATE(151215, 'RRMMDD HHMISS') FROM DUAL;
