SELECT SYSDATE
FROM DUAL;

SELECT LENGTH('오라클'), LENGTHB('오라클')
FROM DUAL;

SELECT LENGTH('oracle'), LENGTHB('oracle')
FROM DUAL;

SELECT EMP_NAME, LENGTH(EMP_NAME), LENGTHB(EMP_NAME), EMAIL, LENGTH(EMAIL), LENGTHB(EMAIL)
FROM EMPLOYEE;

SELECT INSTR('AAAAAVBBBBBCCCCCE', 'V') FROM DUAL;
SELECT INSTR('AAAAAVBBBBBCCCCCE', 'E') FROM DUAL;
SELECT INSTR('AAAAAVBBBBBCCCCCE', 'V', -1) FROM DUAL;
SELECT INSTR('AAAAAVBBBBBCCCCCE', 'B', 1, 2) FROM DUAL;

SELECT EMAIL, INSTR(EMAIL, '_'), INSTR(EMAIL, '@')
FROM EMPLOYEE;

SELECT SUBSTR('ABCDEFG', 3)
FROM DUAL;

SELECT SUBSTR('SGDSHSDHS', 1, 4)
FROM DUAL;

SELECT EMP_NAME, SUBSTR(EMP_NO, 8, 1)
FROM EMPLOYEE
WHERE SUBSTR(EMP_NO, 8, 1) IN ('1', '3');

SELECT EMP_NAME, EMAIL, SUBSTR(EMAIL, 1, INSTR(EMAIL, '@')-1)
FROM EMPLOYEE;

SELECT EMP_NAME, LPAD(EMP_NAME, 15)
FROM EMPLOYEE;

