-- 한국팀 명단 테이블 생성
CREATE TABLE TEAM_KOR (
    BACKNUM NUMBER,
    P_NAME VARCHAR2(10) NOT NULL,
    BIRTHDAY DATE CONSTRAINT BIRTH_NN NOT NULL,
    AGE NUMBER CONSTRAINT AGE_NN NOT NULL,
    HEIGHT VARCHAR2(5) CONSTRAINT HEIGHT_NN NOT NULL,
    WEIGHT VARCHAR2(5) CONSTRAINT WEIGHT_NN NOT NULL,
    POSITION CHAR(2) CONSTRAINT POSIT_NN_OR_CHECK NOT NULL CHECK(POSITION IN ('GK', 'DF', 'MF', 'FW')),
    TEAM VARCHAR2(50),
    CONSTRAINT BACKNUM_OR_PNAME_PK PRIMARY KEY(BACKNUM, P_NAME)
);

-- 주석
COMMENT ON COLUMN TEAM_KOR.BACKNUM IS '등번호';
COMMENT ON COLUMN TEAM_KOR.P_NAME IS '이름';
COMMENT ON COLUMN TEAM_KOR.BIRTHDAY IS '생일';
COMMENT ON COLUMN TEAM_KOR.AGE IS '나이';
COMMENT ON COLUMN TEAM_KOR.HEIGHT IS '키';
COMMENT ON COLUMN TEAM_KOR.WEIGHT IS '체중';
COMMENT ON COLUMN TEAM_KOR.POSITION IS '포지션';
COMMENT ON COLUMN TEAM_KOR.TEAM IS '소속팀';

SELECT * FROM TEAM_KOR;

-- 한국팀 명단 추가
INSERT INTO TEAM_KOR
VALUES(1, '김승규', '90/09/30', 32, '187', '84', 'GK', NULL);
INSERT INTO TEAM_KOR
VALUES(15, '김문환', '95/08/01', 27, '173', '64', 'DF', NULL);
INSERT INTO TEAM_KOR
VALUES(4, '김민재', '96/11/15', 26, '190', '88', 'DF', '나폴리');
INSERT INTO TEAM_KOR
VALUES(19, '김영권', '90/02/27', 32, '186', '83', 'DF', '울산현대');
INSERT INTO TEAM_KOR
VALUES(3, '김진수', '92/06/13', 30, '177', '68', 'DF', '전북현대');
INSERT INTO TEAM_KOR
VALUES(5, '정우영', '89/12/14', 32, '186', '78', 'MF', NULL);
INSERT INTO TEAM_KOR
VALUES(6, '황인범', '96/09/20', 26, '177', '70', 'MF', NULL);
INSERT INTO TEAM_KOR
VALUES(18, '이강인', '01/02/19', 21, '173', '63', 'MF', '마요르카');
INSERT INTO TEAM_KOR
VALUES(7, '손흥민', '92/07/08', 30, '183', '78', 'FW', '토트넘');
INSERT INTO TEAM_KOR
VALUES(11, '황희찬', '96/01/26', 26, '177', '77', 'FW', '울버햄튼');
INSERT INTO TEAM_KOR
VALUES(9, '조규성', '98/01/25', 24, '189', '82', 'FW', '전북 현대');

-- 소속팀 테이블 생성
CREATE TABLE TEAM(
    TEAM_NAME VARCHAR2(50) CONSTRAINT TN_NN NOT NULL PRIMARY KEY,
    LEAGUE VARCHAR2(30) CONSTRAINT LEAGUE_NN NOT NULL
);

-- 주석
COMMENT ON COLUMN TEAM.TEAM_NAME IS '소속팀';
COMMENT ON COLUMN TEAM.LEAGUE IS '소속리그';

SELECT * FROM TEAM;

-- 소속팀 값 추가
INSERT INTO TEAM
VALUES('토트넘', 'EPL');
INSERT INTO TEAM
VALUES('울버햄튼', 'EPL');
INSERT INTO TEAM
VALUES('나폴리', 'SERIE A');
INSERT INTO TEAM
VALUES('전북현대', 'K-LEAGUE');
INSERT INTO TEAM
VALUES('울산현대', 'K-LEAGUE');
INSERT INTO TEAM
VALUES('마요르카', 'LALIGA');

-- 한국 선수들이 어느 리그에서 뛰는 지 검색하는 쿼리문
SELECT P_NAME, LEAGUE
FROM TEAM_KOR
JOIN TEAM ON(TEAM = TEAM_NAME);
